import type { ActionContext, ActionHandler } from "../types";
import { sendEmail } from "../../../email-sender";
import { getMailboxStub, generateMessageId, stripHtmlToText, escapeHtml } from "../../email-helpers";
import { Folders } from "../../../../shared/folders";

const URL_REGEX = /https?:\/\/[^\s<>"]+/g;
const MAX_PAGE_TEXT_LENGTH = 6000;

/**
 * Extract URLs from the cleaned subject line and email body.
 * Checks the subject first (most likely location), then the body.
 */
function extractUrls(subject: string, body: string): string[] {
	const urls = new Set<string>();
	for (const match of subject.matchAll(URL_REGEX)) urls.add(match[0]);
	for (const match of body.matchAll(URL_REGEX)) urls.add(match[0]);
	return [...urls];
}

/**
 * Fetch a web page and return its text content.
 * Returns null if the fetch fails or the response is not HTML/text.
 */
async function fetchPageText(url: string): Promise<string | null> {
	try {
		const response = await fetch(url, {
			headers: { "User-Agent": "Mozilla/5.0 (compatible; EmailSummaryBot/1.0)" },
			redirect: "follow",
		});

		if (!response.ok) {
			console.warn(`[Summary] Failed to fetch ${url}: ${response.status}`);
			return null;
		}

		const contentType = response.headers.get("content-type") || "";
		if (!contentType.includes("text/html") && !contentType.includes("text/plain")) {
			console.warn(`[Summary] Unsupported content type for ${url}: ${contentType}`);
			return null;
		}

		const html = await response.text();
		const text = stripHtmlToText(html);
		return text.slice(0, MAX_PAGE_TEXT_LENGTH);
	} catch (e) {
		console.error(`[Summary] Error fetching ${url}:`, (e as Error).message);
		return null;
	}
}

/**
 * [SUMMARY] action handler.
 *
 * 1. Extracts a URL from the subject or body
 * 2. Fetches the page content
 * 3. Summarizes it using Workers AI
 * 4. Sends a reply email with the summary and stores it in the Sent folder
 */
export const handleSummary: ActionHandler = async (ctx: ActionContext) => {
	const urls = extractUrls(ctx.subject, ctx.body);

	if (urls.length === 0) {
		console.warn(`[Summary] No URL found in email ${ctx.emailId}, skipping`);
		return;
	}

	const targetUrl = urls[0];
	console.log(`[Summary] Processing URL: ${targetUrl}`);

	const pageText = await fetchPageText(targetUrl);
	if (!pageText) {
		console.warn(`[Summary] Could not extract text from ${targetUrl}, skipping`);
		return;
	}

	// Summarize with Workers AI
	// Workers AI binding — types are generated by `wrangler types`
	const aiResponse = await ctx.env.AI.run("@cf/meta/llama-3.1-8b-instruct-fast" as any, {
		messages: [
			{
				role: "system",
				content:
					"You are a helpful assistant. Summarize the following web page content concisely. " +
					"Focus on the key points, main arguments, and important takeaways. " +
					"Use bullet points for clarity. Keep it under 300 words.",
			},
			{
				role: "user",
				content: `Summarize this page (${targetUrl}):\n\n${pageText}`,
			},
		],
	});

	const summary = typeof aiResponse === "string" ? aiResponse : (aiResponse as { response?: string }).response || "";

	if (!summary) {
		console.error(`[Summary] AI returned empty summary for ${targetUrl}`);
		return;
	}

	// Build the reply email
	const replySubject = `Summary: ${ctx.subject}`;
	const escapedUrl = escapeHtml(targetUrl);
	const escapedSummary = escapeHtml(summary);

	const textBody = `Here's a summary of ${targetUrl}:\n\n${summary}`;
	const htmlBody = `
		<div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px;">
			<p>Here's a summary of <a href="${escapedUrl}">${escapedUrl}</a>:</p>
			<div style="background: #f6f8fa; border-radius: 6px; padding: 16px; margin: 12px 0; white-space: pre-wrap;">${escapedSummary}</div>
		</div>
	`.trim();

	// Store the reply in the Sent folder so it appears in the inbox UI
	const fromDomain = ctx.mailboxId.split("@")[1];
	if (!fromDomain) {
		console.error(`[Summary] Invalid mailbox address: ${ctx.mailboxId}`);
		return;
	}

	const { messageId, outgoingMessageId } = generateMessageId(fromDomain);
	const stub = getMailboxStub(ctx.env, ctx.mailboxId);

	await stub.createEmail(Folders.SENT, {
		id: messageId,
		subject: replySubject,
		sender: ctx.mailboxId,
		recipient: ctx.sender,
		cc: null,
		bcc: null,
		date: new Date().toISOString(),
		body: htmlBody,
		in_reply_to: ctx.emailId,
		email_references: JSON.stringify([ctx.emailId]),
		thread_id: ctx.emailId,
		message_id: outgoingMessageId,
		raw_headers: JSON.stringify([
			{ key: "from", value: ctx.mailboxId },
			{ key: "to", value: ctx.sender },
			{ key: "subject", value: replySubject },
			{ key: "date", value: new Date().toISOString() },
			{ key: "message-id", value: `<${outgoingMessageId}>` },
			{ key: "in-reply-to", value: `<${ctx.emailId}>` },
			{ key: "references", value: `<${ctx.emailId}>` },
		]),
	}, []);

	// Send the actual email
	await sendEmail(ctx.env.EMAIL, {
		to: ctx.sender,
		from: ctx.mailboxId,
		subject: replySubject,
		text: textBody,
		html: htmlBody,
		headers: {
			"In-Reply-To": `<${ctx.emailId}>`,
			References: `<${ctx.emailId}>`,
		},
	});

	console.log(`[Summary] Sent summary of ${targetUrl} to ${ctx.sender}`);
};
